apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazar-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lazar-operator
  template:
    metadata:
      labels:
        name: lazar-operator
    spec:
      serviceAccountName: lazar-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: informaticsmatters/lazar-operator:0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: informaticsmatters/lazar-operator:0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: lazar-operator
      volumes:
        - name: runner
          emptyDir: {}
