---

- name: Set Lazar objects state={{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name)|from_yaml }}"
  when: item.api_exists|default(True)
  loop:
  - name: deployment.yaml.j2
  - name: image-stream.yaml.j2
  - name: route.yaml.j2
  - name: service.yaml.j2
